# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_info',
            new_name='project_objective',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='start_time',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_title',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
